module.exports = {
  env: {
    GEO_LOCATION_API: process.env.GEO_LOCATION_API,
    GOV_US_API_KEY: process.env.GOV_US_API_KEY,
    AWS_PROJECT_REGION: process.env.AWS_PROJECT_REGION,
    AWS_COGNITO_IDENTITY_POOL_ID: process.env.AWS_COGNITO_IDENTITY_POOL_ID,
    AWS_COGNITO_REGION: process.env.AWS_COGNITO_REGION,
    AWS_USER_POOLS_ID: process.env.AWS_USER_POOLS_ID,
    AWS_USER_POOLS_WEB_CLIENT_ID: process.env.AWS_USER_POOLS_WEB_CLIENT_ID,
    AWS_APPSYNC_GRAPHQL_ENDPOINT: process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT,
    AWS_APPSYNC_REGION: process.env.AWS_APPSYNC_REGION,
    AWS_APPSYNC_AUTHENTICATION_TYPE:
      process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,
  },
};
