/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:107a42cf-91fd-444a-ae6b-ffa5f7ac1044",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_FmobeOJCo",
    "aws_user_pools_web_client_id": "22i2scff242il7m6o6ctp0ivoj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yqtdxsvxendwfpz2x2vyexoccy.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "content192451-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
