/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  // "aws_project_region": "ca-central-1",
  // "aws_cognito_identity_pool_id": "ca-central-1:107a42cf-91fd-444a-ae6b-ffa5f7ac1044",
  // "aws_cognito_region": "ca-central-1",
  // "aws_user_pools_id": "ca-central-1_FmobeOJCo",
  // "aws_user_pools_web_client_id": "22i2scff242il7m6o6ctp0ivoj",
  // "oauth": {},
  // "aws_appsync_graphqlEndpoint": "https://yqtdxsvxendwfpz2x2vyexoccy.appsync-api.ca-central-1.amazonaws.com/graphql",
  // "aws_appsync_region": "ca-central-1",
  // "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
  aws_project_region: process.env.AWS_PROJECT_REGION,
  aws_cognito_identity_pool_id: process.env.AWS_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: process.env.AWS_COGNITO_REGION,
  aws_user_pools_id: process.env.AWS_USER_POOLS_ID,
  aws_user_pools_web_client_id: process.env.AWS_USER_POOLS_WEB_CLIENT_ID,
  oauth: {},
  aws_appsync_graphqlEndpoint: process.env.AWS_APPSYNC_GRAPHQL_ENDPOINT,
  aws_appsync_region: process.env.AWS_APPSYNC_REGION,
  aws_appsync_authenticationType: process.env.AWS_APPSYNC_AUTHENTICATION_TYPE,
};

export default awsmobile;
