/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:e00815c4-6036-4ee8-9b78-b5dd196ac795",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_juJlHIJil",
    "aws_user_pools_web_client_id": "2r6o0josmvjbgt7joab2bnn2th",
    "oauth": {
        "domain": "welobbyf76746fc-f76746fc-dev.auth.ca-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://crea-ten.vercel.app/",
        "redirectSignOut": "https://crea-ten.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
